# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c95edf5497ebcd397bf3f658c6d1feb03ded3d9994b767696fe18ce9146f71f6e77a6b58f8c8cd8845b302bb994801337d396b9a6c07f38131acb2d24491306

test:
  secret_key_base: bc666378111729863ac42dcb57b006a922c124e6ab259c5f85661f522e5e5c3fdb200428127cd2bb8e087fbc88752a724b7f57a30717d93856ca135b6d60b807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
